-- Views genéricas de relatório do representante (Área Externa / portal).
-- Fonte: adaptadas dos rascunhos guess_representantes_001027_* (piloto),
-- removendo o filtro por NOME e a data hardcoded, e expondo cod_representante
-- (código REAL do rep) como 1a coluna. O motor filtra WHERE cod_representante=@cod.
-- Vivem em GUESS_PRODUCAO.dbo (mesmo DB das tabelas-fonte). Aplicar: node apply-rep-views.js
--
-- SEGURANÇA DO ESCOPO (faturamentos/clientes): a fonte só tem o NOME do rep, não
-- o código. Para NUNCA fundir reps homônimos (um ver dado do outro), o código é
-- derivado só de nome ATIVO e ÚNICO (subquery HAVING COUNT(*)=1). Nome ativo
-- ambíguo NÃO gera código → a linha não aparece p/ ninguém (nega na dúvida, não
-- vaza). financeiro usa COD_REPRESENTANTE nativo, não precisa disso.

-- ===== v_p2p_rep_faturamentos =====
CREATE OR ALTER VIEW dbo.v_p2p_rep_faturamentos AS
SELECT R_REP.cod AS cod_representante, FATURAMENTO.NOME_CLIFOR, FATURAMENTO.NF_SAIDA,  FATURAMENTO.SERIE_NF, FATURAMENTO.EMISSAO, FATURAMENTO.QTDE_TOTAL,  CONVERT(NUMERIC(14, 2), FATURAMENTO.VALOR_TOTAL * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) 
VALOR_TOTAL,   FATURAMENTO.REPRESENTANTE, COND_ATAC_PGTOS.DESC_COND_PGTO,  FATURAMENTO.GERENTE,  CONVERT(NUMERIC(14, 2), FATURAMENTO.ENCARGO * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) ENCARGO,  CONVERT(NUMERIC(14, 2), 
FATURAMENTO.DESCONTO * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) DESCONTO,   FATURAMENTO.NOTA_IMPRESSA, NATUREZAS_SAIDAS.DESC_NATUREZA,  FATURAMENTO.ACERTO_CONTAS_P_R, FATURAMENTO.FILIAL,  FATURAMENTO.COMISSAO,  FATURAMENTO.COMISSAO_GERENTE, FATURAMENTO.TRANSPORTADORA, FATURAMENTO.DATA_SAIDA, 
CONVERT(NUMERIC(14, 2), FATURAMENTO.FRETE * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) FRETE,   CONVERT(NUMERIC(14, 2), FATURAMENTO.SEGURO * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) SEGURO,  
FATURAMENTO.FATURA, FATURAMENTO.NF_FATURA, FATURAMENTO.CONFERIDO, FATURAMENTO.CONFERIDO_POR,  FATURAMENTO.ENTREGA_CIF, FATURAMENTO.NOTA_CANCELADA,  
CONVERT(NUMERIC(14, 2), FATURAMENTO.IRRF * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) IRRF,   FATURAMENTO.IRRF_RET_FONTE, FATURAMENTO.DEVOLUCAO,  CONVERT(NUMERIC(14, 2), FATURAMENTO.ICMS * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) ICMS,   
CONVERT(NUMERIC(14, 2), FATURAMENTO.IPI_VALOR * CASE WHEN CAMBIO_NA_DATA IS NULL OR CAMBIO_NA_DATA = 0 THEN 1 ELSE CAMBIO_NA_DATA END) IPI_VALOR, CAMBIO_NA_DATA, MOEDA, TIMESTAMP, CONVERT(NUMERIC(14, 2), 0) AS VALOR_PRODUCAO, CONVERT(NUMERIC(14,2), 0) AS DIF_PRODUCAO, VALOR_TOTAL AS VALOR_MOEDA 
FROM DBO.FATURAMENTO FATURAMENTO,  DBO.NATUREZAS_SAIDAS NATUREZAS_SAIDAS,  DBO.COND_ATAC_PGTOS COND_ATAC_PGTOS, (SELECT RTRIM(REPRESENTANTE) AS nm, MIN(LTRIM(RTRIM(COD_REPRESENTANTE))) AS cod FROM DBO.REPRESENTANTES WHERE ISNULL(INATIVO,0)=0 GROUP BY RTRIM(REPRESENTANTE) HAVING COUNT(*)=1) R_REP WHERE NATUREZAS_SAIDAS.NATUREZA_SAIDA = FATURAMENTO.NATUREZA_SAIDA    AND COND_ATAC_PGTOS.CONDICAO_PGTO = FATURAMENTO.CONDICAO_PGTO
AND R_REP.nm = RTRIM(FATURAMENTO.REPRESENTANTE)
GO

-- ===== v_p2p_rep_financeiro =====
CREATE OR ALTER VIEW dbo.v_p2p_rep_financeiro AS

SELECT LTRIM(RTRIM(A.COD_REPRESENTANTE)) AS cod_representante, B.CONTA_PORTADOR, B.EMPRESA, B.LANCAMENTO, B.ITEM, B.ID_PARCELA, B.VENCIMENTO_REAL, A.FATURA, B.VALOR_A_RECEBER, B.VALOR_ORIGINAL, A.EMISSAO, POSICAO = CASE WHEN B.VALOR_A_RECEBER = 0 THEN 'RECEBIDO' ELSE CASE WHEN  DATEDIFF(DD, B.VENCIMENTO_REAL, GETDATE()) > 
0 THEN 'VENCIDOS' WHEN  DATEDIFF(DD, B.VENCIMENTO_REAL, GETDATE()) < 0 THEN 'A VENCER' WHEN DATEDIFF(DD, B.VENCIMENTO_REAL, GETDATE()) = 0 THEN 'VENCENDO HOJE' END END, B.NUMERO_BANCARIO, C.FILIAL, DESC_CONTA_PORTADOR = D.DESC_CONTA, E.DATA_LANCAMENTO, 
B.VENCIMENTO, A.COD_REPRESENTANTE_GERENTE, REPRESENTANTE = F.REPRESENTANTE, GERENTE = G.REPRESENTANTE, A.COMISSAO, A.COMISSAO_GERENTE, A.JUROS_POR_ATRASO, A.MULTA_POR_ATRASO, A.MOEDA, A.PORCENTAGEM_ACERTO, B.VALOR_ORIGINAL_PADRAO, 
H.VALOR_A_RECEBER_PADRAO, H.SALDO_PRINCIPAL_DEVIDO, H.SALDO_MULTA_GERADA, H.SALDO_JUROS_GERADO, H.SALDO_DESCONTO_CONCEDIDO, H.SALDO_PRINCIPAL_DEVIDO_PADRAO, H.SALDO_MULTA_GERADA_PADRAO, H.SALDO_JUROS_GERADO_PADRAO, H.SALDO_DESCONTO_CONCEDIDO_PADRAO, A.DOCUMENTO, A.CAMBIO_NA_DATA_EMISSAO, B.DIAS_PRORROGADOS, B.DATA_DESCONTO_VENC, B.DESCONTO_VENC, B.INDICA_PROTESTO, B.BANCO, B.AGENCIA, B.CAMBIO_FIXO_PGTO, CONVERT(NUMERIC(14,2),0) AS SALDO_CORRIGIDO, CONVERT(BIT,CASE WHEN I.CONTA_CONTABIL=B.CONTA_PORTADOR THEN 1 ELSE 0 END) AS EM_CARTEIRA , CONVERT(BIT,CASE WHEN I.CONTA_CONTABIL=B.CONTA_PORTADOR THEN 0 ELSE 1 END) AS EM_COBRANCA, H.TOTAL_PRINCIPAL_RECEBIDO_PADRAO, H.TOTAL_MULTA_PAGA_PADRAO, H.TOTAL_JUROS_PAGO_PADRAO,TOTAL_DESCONTO_EFETIVADO_PADRAO, 

PERIODO = CASE WHEN B.VALOR_A_RECEBER = 0 THEN DATEDIFF(DD, B.VENCIMENTO_REAL, H.DATA_PAGAMENTO) ELSE DATEDIFF(DD, B.VENCIMENTO_REAL, GETDATE()) END, CADASTRO_CLI_FOR.NOME_CLIFOR, TOTAL_JUROS_GERADO, CADASTRO_CLI_FOR.BANCO BANCO_TERCEIRO, E.TIPO_MOVIMENTO    
FROM CTB_A_RECEBER_FATURA A (NOLOCK) 
JOIN CTB_A_RECEBER_PARCELA B (NOLOCK) ON A.EMPRESA = B.EMPRESA AND A.LANCAMENTO = B.LANCAMENTO AND A.ITEM = B.ITEM 
JOIN FILIAIS C (NOLOCK) ON A.COD_EMISSOR = C.COD_FILIAL 
JOIN CTB_CONTA_PLANO D (NOLOCK) ON B.CONTA_PORTADOR = D.CONTA_CONTABIL  
JOIN CTB_LANCAMENTO E (NOLOCK) ON E.EMPRESA = A.EMPRESA AND E.LANCAMENTO = A.LANCAMENTO   
LEFT JOIN REPRESENTANTES F (NOLOCK) ON A.COD_REPRESENTANTE = F.COD_REPRESENTANTE   
LEFT JOIN REPRESENTANTES G (NOLOCK) ON A.COD_REPRESENTANTE_GERENTE = G.COD_REPRESENTANTE 
LEFT JOIN W_CTB_A_RECEBER_PARCELA_SALDO H (NOLOCK) ON H.EMPRESA = B.EMPRESA AND H.LANCAMENTO = B.LANCAMENTO AND H.ITEM = B.ITEM AND H.ID_PARCELA = B.ID_PARCELA 
JOIN CTB_LANCAMENTO_ITEM I (NOLOCK) ON A.EMPRESA = I.EMPRESA AND A.LANCAMENTO = I.LANCAMENTO AND A.ITEM = I.ITEM 
JOIN CADASTRO_CLI_FOR ON CADASTRO_CLI_FOR.COD_CLIFOR = A.COD_CLIFOR     
WHERE  B.Valor_A_Receber <> 0
GO

-- ===== v_p2p_rep_clientes =====
CREATE OR ALTER VIEW dbo.v_p2p_rep_clientes as

SELECT R_REP.cod AS cod_representante, CADASTRO_CLI_FOR.NOME_CLIFOR,
       CADASTRO_CLI_FOR.CLIFOR, 
       CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.CGC_CPF, 
       CLIENTES_ATACADO.CONTA_CONTABIL, 
       CONTAS_PLANO.DESC_CONTA, 
       CADASTRO_CLI_FOR.PJ_PF, 
       CADASTRO_CLI_FOR.RG_IE, 
       CADASTRO_CLI_FOR.CEP, 
       CADASTRO_CLI_FOR.ENDERECO, 
       CADASTRO_CLI_FOR.CIDADE, 
       CADASTRO_CLI_FOR.BAIRRO, 
       CADASTRO_CLI_FOR.UF, 
       CADASTRO_CLI_FOR.TELEFONE1, 
       CADASTRO_CLI_FOR.PAIS, 
       CADASTRO_CLI_FOR.DDI, 
       CADASTRO_CLI_FOR.TELEFONE2, 
       CADASTRO_CLI_FOR.FAX, 
       CADASTRO_CLI_FOR.DDD1, 
       CADASTRO_CLI_FOR.RAMAL1, 
       CADASTRO_CLI_FOR.RAMAL2, 
       CADASTRO_CLI_FOR.DDD2, 
       CADASTRO_CLI_FOR.COBRANCA_ENDERECO, 
       CADASTRO_CLI_FOR.COBRANCA_CIDADE, 
       CADASTRO_CLI_FOR.COBRANCA_BAIRRO, 
       CADASTRO_CLI_FOR.DDDFAX, 
       CADASTRO_CLI_FOR.COBRANCA_UF, 
       CADASTRO_CLI_FOR.COBRANCA_CEP, 
       CADASTRO_CLI_FOR.COBRANCA_TELEFONE, 
       CADASTRO_CLI_FOR.ENTREGA_ENDERECO, 
       CADASTRO_CLI_FOR.ENTREGA_BAIRRO, 
       CADASTRO_CLI_FOR.ENTREGA_CIDADE, 
       CADASTRO_CLI_FOR.ACEITA_DIAS_FIXO, 
       CADASTRO_CLI_FOR.ENTREGA_UF, 
       CADASTRO_CLI_FOR.ENTREGA_CEP, 
       CADASTRO_CLI_FOR.ENTREGA_TELEFONE, 
       CADASTRO_CLI_FOR.COBRANCA_DDD, 
       CADASTRO_CLI_FOR.CONTATO, 
       CADASTRO_CLI_FOR.COBRANCA_CGC, 
       CADASTRO_CLI_FOR.CADASTRAMENTO, 
       CADASTRO_CLI_FOR.COBRANCA_IE, 
       CADASTRO_CLI_FOR.ANIVERSARIO, 
       CADASTRO_CLI_FOR.INDICA_FORNECEDOR, 
       CADASTRO_CLI_FOR.INDICA_CLIENTE, 
       CADASTRO_CLI_FOR.IND_REPRESENTANTE, 
       CADASTRO_CLI_FOR.INDICA_FILIAL, 
       CADASTRO_CLI_FOR.ENTREGA_DDD, 
       CADASTRO_CLI_FOR.ENTREGA_CGC, 
       CLIENTES_ATACADO.CLIFOR as CLIFOR_CLIENTES_ATACADO, 
       CLIENTES_ATACADO.CGC_CPF as CGC_CPF_CLIENTES_ATACADO, 
       ISNULL(CLIENTES_ATACADO.ACEITA_JUNTAR_PED, 0)             AS 
       ACEITA_JUNTAR_PED, 
       CLIENTES_ATACADO.TIPO_BLOQUEIO, 
       CLIENTES_ATACADO.BLOQUEIO_FATURAMENTO, 
       CLIENTES_ATACADO.BLOQUEIO_EXPEDICAO, 
       CLIENTES_ATACADO.BLOQUEIO_PEDIDOS, 
       CLIENTES_ATACADO.LIMITE_CREDITO, 
       CLIENTES_ATACADO.SEM_CREDITO, 
       CLIENTES_ATACADO.PRIORIDADE, 
       CLIENTES_ATACADO.TIPO, 
       CLIENTES_ATACADO.FRETE_A_PAGAR, 
       CLIENTES_ATACADO.CONCEITO, 
       CLIENTES_ATACADO.FILIAL, 
       CLIENTES_ATACADO.TRANSPORTADORA, 
       CLIENTES_ATACADO.PONTUALIDADE, 
       CLIENTES_ATACADO.MATRIZ_CLIENTE, 
       CLIENTES_ATACADO.CLIENTE_ATACADO, 
       CADASTRO_CLI_FOR.ENTREGA_IE, 
       CLIENTES_ATACADO.REGIAO, 
       CLIENTES_ATACADO.CONDICAO_PGTO, 
       CADASTRO_CLI_FOR.BANCO, 
       CADASTRO_CLI_FOR.CC_AGENCIA, 
       CADASTRO_CLI_FOR.CC_CONTA, 
       CADASTRO_CLI_FOR.CC_NOME_AGENCIA, 
       CADASTRO_CLI_FOR.REF_ANTERIOR, 
       CLIENTES_ATACADO.NUMERO_PEDIDOS, 
       CLIENTES_ATACADO.DATA_MAIOR_PEDIDO, 
       CLIENTES_ATACADO.MAIOR_PEDIDO, 
       CLIENTES_ATACADO.MAIOR_SALDO, 
       CLIENTES_ATACADO.DATA_MAIOR_SALDO, 
       CLIENTES_ATACADO.DATA_MAIOR_ATRASO, 
       CLIENTES_ATACADO.NUMERO_ATRASOS, 
       CLIENTES_ATACADO.MAIOR_ATRASO, 
       CLIENTES_ATACADO.PGTOS_CARTORIO, 
       CLIENTES_ATACADO.NUMERO_DEVOLUCOES, 
       CLIENTES_ATACADO.MAIOR_DEVOLUCAO, 
       CLIENTES_ATACADO.NUMERO_PRORROGACOES, 
       CLIENTES_ATACADO.MAIOR_PRORROGACAO, 
       CLIENTES_ATACADO.MAIOR_QTDE_DEV, 
       CLIENTES_ATACADO.DATA_MAIOR_QTDE_DEV, 
       CLIENTES_ATACADO.DATA_MAIOR_DEVOLUCAO, 
       CLIENTES_ATACADO.MAIOR_QTDE_PEDIDO, 
       CLIENTES_ATACADO.DATA_MAIOR_QTDE_PEDIDO, 
       CLIENTES_ATACADO.DESCONTO_FATURAMENTO, 
       CADASTRO_CLI_FOR.CARTEIRA, 
       CADASTRO_CLI_FOR.OBS_DE_FATURAMENTO, 
       CLIENTES_ATACADO.OBS, 
       CADASTRO_CLI_FOR.EMAIL, 
       CLIENTES_ATACADO.MOEDA, 
       CLIENTES_ATACADO.INATIVO as CLIENTES_ATACADO_INATIVO, 
       CADASTRO_CLI_FOR.ATUALIZACAO_EXPORTAR, 
       CADASTRO_CLI_FOR.DATA_EXPORTACAO, 
       CADASTRO_CLI_FOR.STATUS_ENVIO, 
       CADASTRO_CLI_FOR.INATIVO as CADASTRO_CLI_FOR_INATIVO, 
       
       CADASTRO_CLI_FOR.ENTREGA_PAIS, 
       CADASTRO_CLI_FOR.COBRANCA_PAIS, 
       BANCOS.NOME_BANCO, 
       CADASTRO_CLI_FOR.ENTREGA_DDI, 
       CADASTRO_CLI_FOR.COBRANCA_DDI, 
       CLIENTES_ATACADO.COD_CLIENTE, 
       
       CLIENTES_ATACADO.INDICA_FRANQUIA, 
       CLIENTES_ATACADO.CODIGO_TAB_PRECO, 
       CLIENTES_ATACADO.FATOR_CUSTO_FRANQUIA, 
       CLIENTES_ATACADO.DESCONTO_PEDIDO_VENDA, 
       CLIENTES_ATACADO.SEGURO_NUMERO_CONTRATO, 
       CLIENTES_ATACADO.SEGURO_NUMERO_CLIENTE, 
       CLIENTES_ATACADO.SEGURO_VALIDADE, 
       CADASTRO_CLI_FOR.ISENTO_IPI, 
       CADASTRO_CLI_FOR.ISENTO_ICMS, 
       CLIENTES_ATACADO.MAIOR_VALOR_FATURADO, 
       CLIENTES_ATACADO.DATA_MAIOR_VALOR_FATURADO, 
       CADASTRO_CLI_FOR.MESES_SEM_VENCIMENTO, 
       CADASTRO_CLI_FOR.DATA_FIXA_PGTO, 
       CADASTRO_CLI_FOR.ACEITA_AGRUPAR_FATURA, 
       CADASTRO_CLI_FOR.NUMERO_VIAS_FATURA, 
       CADASTRO_CLI_FOR.REPORT_FATURA, 
       CADASTRO_CLI_FOR.DIAS_ANTECIPACAO_PGTO, 
       CADASTRO_CLI_FOR.PASSWEB, 
       CADASTRO_CLI_FOR.VENCIMENTO_PASSWEB, 
       FILIAIS.EMPRESA, 
       FILIAIS.TIPO_FILIAL, 
       ISNULL(CADASTRO_CLI_FOR.POSSUI_RECARGO, 0)                AS 
       POSSUI_RECARGO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_PEDIDO, 0)     AS 
       EXPEDICAO_COMPLETO_PEDIDO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_PACK, 0)       AS 
       EXPEDICAO_COMPLETO_PACK, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_TAMANHOS, 0)   AS 
       EXPEDICAO_COMPLETO_TAMANHOS, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_COR, 0)        AS 
       EXPEDICAO_COMPLETO_COR, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_COORDENADO, 0) AS 
       EXPEDICAO_COMPLETO_COORDENADO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_PORCENTAGEM_MAIOR, 0)   AS 
       EXPEDICAO_PORCENTAGEM_MAIOR, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_PORCENTAGEM_MINIMA, 0)  AS 
       EXPEDICAO_PORCENTAGEM_MINIMA, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_PORCENTAGEM_TIPO, 0)    AS 
       EXPEDICAO_PORCENTAGEM_TIPO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_VALOR_MAXIMO, 0)        AS 
       EXPEDICAO_VALOR_MAXIMO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_CARTELA, 0)    AS 
       EXPEDICAO_COMPLETO_CARTELA, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_COMPLETO_FAIXAS, 0)     AS 
       EXPEDICAO_COMPLETO_FAIXAS, 
       CADASTRO_CLI_FOR.INDICADOR_FISCAL_TERCEIRO, 
       CTB_LX_INDICADOR_FISCAL_TERCEIRO.DESCRICAO_FISCAL_TERCEIRO, 
       CLIENTES_ATACADO.CTB_CONTA_CONTABIL, 
       CTB_CONTA_PLANO.DESC_CONTA                                AS 
       CTB_DESC_CONTA, 
       CADASTRO_CLI_FOR.COD_CLIFOR, 
       CADASTRO_CLI_FOR.COBRANCA_RAZAO_SOCIAL, 
       CADASTRO_CLI_FOR.ENTREGA_RAZAO_SOCIAL, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_PORC_ADEQUACAO, 0) 
       EXPEDICAO_PORC_ADEQUACAO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_QTDE_ADEQUACAO, 0) 
       EXPEDICAO_QTDE_ADEQUACAO, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_ADEQUACAO_COR, 0) 
       EXPEDICAO_ADEQUACAO_COR, 
       ISNULL(CLIENTES_ATACADO.EXPEDICAO_ADEQUACAO_TAMANHO, 0) 
       EXPEDICAO_ADEQUACAO_TAMANHO, 
       CADASTRO_CLI_FOR.ID_EXCECAO_GRUPO, 
       CTB_EXCECAO_GRUPO.DESC_EXCECAO_GRUPO, 
       ISNULL(CADASTRO_CLI_FOR.AGRUPAMENTO_ITENS, 0)             AS 
       AGRUPAMENTO_ITENS, 
       CLIENTES_ATACADO.INDICADOR_VENDA, 
       CADASTRO_CLI_FOR.COMPLEMENTO, 
       CADASTRO_CLI_FOR.COBRANCA_COMPLEMENTO, 
       CADASTRO_CLI_FOR.ENTREGA_COMPLEMENTO, 
       CADASTRO_CLI_FOR.NUMERO, 
       CADASTRO_CLI_FOR.COBRANCA_NUMERO, 
       CADASTRO_CLI_FOR.ENTREGA_NUMERO 
FROM   CLIENTES_ATACADO 
       INNER JOIN CADASTRO_CLI_FOR 
               ON CLIENTES_ATACADO.CLIENTE_ATACADO = 
                  CADASTRO_CLI_FOR.NOME_CLIFOR 
       LEFT JOIN CONTAS_PLANO 
              ON CLIENTES_ATACADO.CONTA_CONTABIL = CONTAS_PLANO.CONTA_CONTABIL 
       LEFT JOIN CTB_CONTA_PLANO 
              ON CLIENTES_ATACADO.CTB_CONTA_CONTABIL = 
                 CTB_CONTA_PLANO.CONTA_CONTABIL 
       LEFT JOIN BANCOS 
              ON CADASTRO_CLI_FOR.BANCO = BANCOS.BANCO 
       INNER JOIN FILIAIS 
               ON CLIENTES_ATACADO.FILIAL = FILIAIS.FILIAL 
       LEFT JOIN CTB_LX_INDICADOR_FISCAL_TERCEIRO 
              ON CADASTRO_CLI_FOR.INDICADOR_FISCAL_TERCEIRO = 
                 CTB_LX_INDICADOR_FISCAL_TERCEIRO.INDICADOR_FISCAL_TERCEIRO 
       LEFT JOIN CTB_EXCECAO_GRUPO 
              ON CADASTRO_CLI_FOR.ID_EXCECAO_GRUPO = 
                 CTB_EXCECAO_GRUPO.ID_EXCECAO_GRUPO 

				 INNER JOIN PROP_REPRESENTANTES
       ON PROP_REPRESENTANTES.PROPRIEDADE = '00094'
      AND EXISTS (
            SELECT 1
            FROM STRING_SPLIT(PROP_REPRESENTANTES.VALOR_PROPRIEDADE, ',') AS UFs
            WHERE LTRIM(RTRIM(UFs.value)) = LTRIM(RTRIM(CADASTRO_CLI_FOR.UF))
          )
 INNER JOIN (SELECT RTRIM(REPRESENTANTE) AS nm, MIN(LTRIM(RTRIM(COD_REPRESENTANTE))) AS cod FROM REPRESENTANTES WHERE ISNULL(INATIVO,0)=0 GROUP BY RTRIM(REPRESENTANTE) HAVING COUNT(*)=1) R_REP ON R_REP.nm = RTRIM(PROP_REPRESENTANTES.REPRESENTANTE)
GO
