-- ============================================================
-- Views de integração ERP — criadas no P2P_DB
-- Unem as duas empresas (GUESS_PRODUCAO + DB_HRG3) via cross-database
-- Camada anti-corrupção: o P2P só enxerga estas views, nunca o schema do ERP
-- Reaplicar: rodar este arquivo via apply-erp-views.js
-- ============================================================

-- ---------- FILIAIS ----------
CREATE OR ALTER VIEW dbo.v_p2p_branches AS
SELECT 'GUESS' AS empresa, RTRIM(COD_FILIAL) AS codigo, RTRIM(FILIAL) AS nome,
       RTRIM(CGC_CPF) AS cnpj, RTRIM(TIPO_FILIAL) AS tipo
FROM GUESS_PRODUCAO.dbo.FILIAIS
UNION ALL
SELECT 'HERING', RTRIM(COD_FILIAL), RTRIM(FILIAL), RTRIM(CGC_CPF), RTRIM(TIPO_FILIAL)
FROM DB_HRG3.dbo.FILIAIS;
GO

-- ---------- CENTROS DE CUSTO ----------
CREATE OR ALTER VIEW dbo.v_p2p_cost_centers AS
SELECT 'GUESS' AS empresa, RTRIM(CENTRO_CUSTO) AS codigo,
       RTRIM(DESC_CENTRO_CUSTO) AS nome, INATIVA AS inativo
FROM GUESS_PRODUCAO.dbo.CTB_CENTRO_CUSTO
UNION ALL
SELECT 'HERING', RTRIM(CENTRO_CUSTO), RTRIM(DESC_CENTRO_CUSTO), INATIVA
FROM DB_HRG3.dbo.CTB_CENTRO_CUSTO;
GO

-- ---------- FORNECEDORES ----------
CREATE OR ALTER VIEW dbo.v_p2p_suppliers AS
SELECT 'GUESS' AS empresa, RTRIM(COD_FORNECEDOR) AS codigo, RTRIM(FORNECEDOR) AS nome,
       RTRIM(CGC_CPF) AS cnpj_cpf,
       CASE WHEN LEN(RTRIM(CGC_CPF)) >= 14 THEN 'PJ' ELSE 'PF' END AS tipo_pessoa,
       RTRIM(TIPO) AS tipo, RTRIM(SUBTIPO_FORNECEDOR) AS subtipo,
       RTRIM(CONDICAO_PGTO) AS condicao_pgto, RTRIM(CONTA_CONTABIL) AS conta_contabil,
       INATIVO AS inativo
FROM GUESS_PRODUCAO.dbo.FORNECEDORES
UNION ALL
SELECT 'HERING', RTRIM(COD_FORNECEDOR), RTRIM(FORNECEDOR), RTRIM(CGC_CPF),
       CASE WHEN LEN(RTRIM(CGC_CPF)) >= 14 THEN 'PJ' ELSE 'PF' END,
       RTRIM(TIPO), RTRIM(SUBTIPO_FORNECEDOR), RTRIM(CONDICAO_PGTO),
       RTRIM(CONTA_CONTABIL), INATIVO
FROM DB_HRG3.dbo.FORNECEDORES;
GO

-- ---------- PLANO DE CONTAS ----------
CREATE OR ALTER VIEW dbo.v_p2p_accounts AS
SELECT 'GUESS' AS empresa, RTRIM(CONTA_CONTABIL) AS codigo, RTRIM(DESC_CONTA) AS nome,
       RTRIM(TIPO_CONTA) AS tipo_conta, INDICA_CTRL_ORCAMENTO AS controla_orcamento,
       INATIVA AS inativo
FROM GUESS_PRODUCAO.dbo.CTB_CONTA_PLANO
UNION ALL
SELECT 'HERING', RTRIM(CONTA_CONTABIL), RTRIM(DESC_CONTA), RTRIM(TIPO_CONTA),
       INDICA_CTRL_ORCAMENTO, INATIVA
FROM DB_HRG3.dbo.CTB_CONTA_PLANO;
GO

-- ---------- ITENS (catálogo de compras) ----------
CREATE OR ALTER VIEW dbo.v_p2p_items AS
SELECT 'GUESS' AS empresa, RTRIM(CODIGO_ITEM) AS codigo,
       RTRIM(ITEM_DESCRICAO) AS descricao, RTRIM(UNIDADE) AS unidade,
       RTRIM(CONTA_CONTABIL) AS conta_contabil_padrao,
       RTRIM(RATEIO_FILIAL) AS rateio_filial_padrao,
       RTRIM(RATEIO_CENTRO_CUSTO) AS rateio_cc_padrao,
       RTRIM(ITEM_FISCAL_GRUPO) AS grupo, INATIVO AS inativo
FROM GUESS_PRODUCAO.dbo.CADASTRO_ITEM_FISCAL
UNION ALL
SELECT 'HERING', RTRIM(CODIGO_ITEM), RTRIM(ITEM_DESCRICAO), RTRIM(UNIDADE),
       RTRIM(CONTA_CONTABIL), RTRIM(RATEIO_FILIAL), RTRIM(RATEIO_CENTRO_CUSTO),
       RTRIM(ITEM_FISCAL_GRUPO), INATIVO
FROM DB_HRG3.dbo.CADASTRO_ITEM_FISCAL;
GO

-- ---------- RATEIOS DE FILIAL (template + linhas com %) ----------
CREATE OR ALTER VIEW dbo.v_p2p_branch_rateios AS
SELECT 'GUESS' AS empresa, RTRIM(r.RATEIO_FILIAL) AS rateio_codigo,
       RTRIM(r.DESC_RATEIO_FILIAL) AS rateio_descricao, r.INATIVO AS rateio_inativo,
       RTRIM(i.COD_FILIAL) AS filial_codigo, i.PORCENTAGEM AS porcentagem
FROM GUESS_PRODUCAO.dbo.CTB_FILIAL_RATEIO r
JOIN GUESS_PRODUCAO.dbo.CTB_FILIAL_RATEIO_ITEM i ON i.RATEIO_FILIAL = r.RATEIO_FILIAL
UNION ALL
SELECT 'HERING', RTRIM(r.RATEIO_FILIAL), RTRIM(r.DESC_RATEIO_FILIAL), r.INATIVO,
       RTRIM(i.COD_FILIAL), i.PORCENTAGEM
FROM DB_HRG3.dbo.CTB_FILIAL_RATEIO r
JOIN DB_HRG3.dbo.CTB_FILIAL_RATEIO_ITEM i ON i.RATEIO_FILIAL = r.RATEIO_FILIAL;
GO

-- ---------- RATEIOS DE CENTRO DE CUSTO (template + linhas com %) ----------
CREATE OR ALTER VIEW dbo.v_p2p_cc_rateios AS
SELECT 'GUESS' AS empresa, RTRIM(r.RATEIO_CENTRO_CUSTO) AS rateio_codigo,
       RTRIM(r.DESC_RATEIO_CENTRO_CUSTO) AS rateio_descricao, r.INATIVO AS rateio_inativo,
       RTRIM(i.CENTRO_CUSTO) AS centro_custo_codigo, RTRIM(i.COD_FILIAL) AS filial_codigo,
       i.PORCENTAGEM AS porcentagem
FROM GUESS_PRODUCAO.dbo.CTB_CENTRO_CUSTO_RATEIO r
JOIN GUESS_PRODUCAO.dbo.CTB_CENTRO_CUSTO_RATEIO_ITEM i ON i.RATEIO_CENTRO_CUSTO = r.RATEIO_CENTRO_CUSTO
UNION ALL
SELECT 'HERING', RTRIM(r.RATEIO_CENTRO_CUSTO), RTRIM(r.DESC_RATEIO_CENTRO_CUSTO), r.INATIVO,
       RTRIM(i.CENTRO_CUSTO), RTRIM(i.COD_FILIAL), i.PORCENTAGEM
FROM DB_HRG3.dbo.CTB_CENTRO_CUSTO_RATEIO r
JOIN DB_HRG3.dbo.CTB_CENTRO_CUSTO_RATEIO_ITEM i ON i.RATEIO_CENTRO_CUSTO = r.RATEIO_CENTRO_CUSTO;
GO
