SELECT 'LOJA_NOTA_FISCAL' AS origem, CODIGO_FILIAL, NF_NUMERO, SERIE_NF, CODIGO_CLIENTE, EMISSAO,
       VALOR_TOTAL_ITENS, DESCONTO, ENCARGO, FRETE, SEGURO, VALOR_TOTAL,
       CHAVE_NFE, PROTOCOLO_AUTORIZACAO_NFE, DATA_AUTORIZACAO_NFE,
       STATUS_NFE, LOG_STATUS_NFE, LX_STATUS_NOTA_FISCAL, NOTA_CANCELADA,
       INFORMACAO_COMPLEMENTAR
FROM dbo.LOJA_NOTA_FISCAL WITH (NOLOCK)
WHERE CODIGO_FILIAL='000013' AND NF_NUMERO='000108675';

SELECT 'LOJA_VENDA' AS origem, CODIGO_FILIAL, TICKET, DATA_VENDA, TERMINAL, CODIGO_FILIAL_PGTO, TERMINAL_PGTO, LANCAMENTO_CAIXA,
       VALOR_TIKET, VALOR_PAGO, VALOR_VENDA_BRUTA, VALOR_TROCA, VALOR_CANCELADO, SUGESTAO_COD_FORMA_PGTO
FROM dbo.LOJA_VENDA WITH (NOLOCK)
WHERE CODIGO_FILIAL='000013' AND TICKET='00109073';

SELECT 'LOJA_VENDA_PARCELAS' AS origem, CODIGO_FILIAL, TERMINAL, LANCAMENTO_CAIXA, PARCELA, TIPO_PGTO,
       VALOR, VALOR_CANCELADO, VALOR_MOEDA, TROCO, VALOR_PARCELA_FINANC, VALOR_TAC, LX_METODO_PGTO
FROM dbo.LOJA_VENDA_PARCELAS WITH (NOLOCK)
WHERE CODIGO_FILIAL='000013' AND RTRIM(TERMINAL)='01' AND LANCAMENTO_CAIXA='056Q01B'
ORDER BY PARCELA;

SELECT 'SOMA_PARCELAS' AS origem,
       SUM(ISNULL(VALOR,0)) AS soma_valor,
       SUM(ISNULL(TROCO,0)) AS soma_troco,
       SUM(ISNULL(VALOR,0))-SUM(ISNULL(TROCO,0)) AS liquido_pagamento
FROM dbo.LOJA_VENDA_PARCELAS WITH (NOLOCK)
WHERE CODIGO_FILIAL='000013' AND RTRIM(TERMINAL)='01' AND LANCAMENTO_CAIXA='056Q01B';

SELECT 'LOJA_PEDIDO_PGTO' AS origem, PEDIDO, CODIGO_FILIAL_ORIGEM, PARCELA, TIPO_PGTO,
       VALOR, VALOR_CANCELADO, VALOR_MOEDA, TROCO, VALOR_PARCELA_FINANC, VALOR_TAC, LX_METODO_PGTO
FROM dbo.LOJA_PEDIDO_PGTO WITH (NOLOCK)
WHERE PEDIDO = -154633
ORDER BY PARCELA;

SELECT 'SOMA_PEDIDO_PGTO' AS origem,
       SUM(ISNULL(VALOR,0)) AS soma_valor,
       SUM(ISNULL(TROCO,0)) AS soma_troco,
       SUM(ISNULL(VALOR,0))-SUM(ISNULL(TROCO,0)) AS liquido_pagamento
FROM dbo.LOJA_PEDIDO_PGTO WITH (NOLOCK)
WHERE PEDIDO = -154633;
