
CREATE VIEW [dbo].[W_HRG3_CONTAS_PAGAR_PROVISAO] AS

SELECT 
'PEDCOM' AS 'TIPO',
CAST(A.PEDIDO AS VARCHAR(50)) 'ID',
ISNULL(A.REQUERIDO_POR, A.APROVADOR_POR) 'EMITENTE',
A.EMISSAO 'EMISSAO',
C.CLIFOR 'COD_CLIFOR',
RTRIM(A.FORNECEDOR) 'NOME_CLIFOR',
B.CONTA_CONTABIL,
B.DESC_CONSUMIVEL 'DESC_ITEM',
ISNULL(B.RATEIO_FILIAL, E.COD_FILIAL) 'CTB_FILIAL',
B.RATEIO_CENTRO_CUSTO 'CTB_CENTRO_CUSTO',
dbo.HRG3_SOMENTE_NUMEROS(F.ID_PARCELA) 'ID_PARCELA',
A.MOEDA,
(F.PORCENTAGEM/100) * B.VALOR_ORIGINAL 'VALOR_ORIGINAL',
(F.PORCENTAGEM/100) * B.VALOR_ENTREGAR 'VALOR_ENTREGAR',
ISNULL(DATA_CONFIRMACAO, ISNULL(ENTREGA, LIMITE_ENTREGA)) 'VENCIMENTO',
DATEADD(DAY, F.PRAZO_DIAS, ISNULL(DATA_CONFIRMACAO, ISNULL(ENTREGA, LIMITE_ENTREGA)) ) 'VENCIMENTO_REAL',
D.COD_FILIAL,
A.OBS 'OBS',
STATUS_APROVACAO 'STATUS_APROVACAO'
FROM COMPRAS A
INNER JOIN COMPRAS_CONSUMIVEL B ON A.PEDIDO = B.PEDIDO
LEFT JOIN W_HRG3_CADASTRO_CLIFOR_RECENTE C ON RTRIM(A.FORNECEDOR) = RTRIM(C.NOME_CLIFOR)
LEFT JOIN FILIAIS D ON A.FILIAL_A_FATURAR = D.FILIAL
LEFT JOIN FILIAIS E ON A.FILIAL_A_ENTREGAR = E.FILIAL
INNER JOIN W_HRG3_COND_ENT_PGTOS_VERTICAL F ON A.CONDICAO_PGTO = F.CONDICAO_PGTO

UNION ALL

SELECT 
'SV' AS 'TIPO',
CAST(A.SOLICITACAO_VERBA AS VARCHAR(50)) 'ID',
ISNULL(A.VERBA_EMITENTE, A.USUARIO) 'EMITENTE',
A.VERBA_EMISSAO 'EMISSAO',
B.COD_CLIFOR,
RTRIM(C.NOME_CLIFOR) 'NOME_CLIFOR',
B.CONTA_CONTABIL,
DESC_SOLICITACAO_VERBA_ITEM 'DESC_ITEM',
ISNULL(B.RATEIO_FILIAL, B.COD_FILIAL) 'CTB_FILIAL',
B.RATEIO_CENTRO_CUSTO 'CTB_CENTRO_CUSTO',
B.ID_SOLICITACAO_ITEM 'ID_PARCELA',
B.MOEDA,
B.VALOR_ORIGINAL,
B.VALOR_A_PAGAR 'VALOR_ENTREGAR',
B.VENCIMENTO,
B.VENCIMENTO_REAL,
B.COD_FILIAL,
A.VERBA_OBS 'OBS',
LX_VERBA_STATUS 'STATUS_APROVACAO'
FROM CTB_SOLICITACAO_VERBA A
INNER JOIN CTB_SOLICITACAO_VERBA_ITEM B ON A.SOLICITACAO_VERBA = B.SOLICITACAO_VERBA
LEFT JOIN W_HRG3_CADASTRO_CLIFOR_RECENTE C ON B.COD_CLIFOR = C.CLIFOR

