
CREATE VIEW [dbo].[W_CTB_A_PAGAR_PARCELA] 
AS
  -- 13/03/2019 - ADALBERTO (WA)    - ID 99772   - 01.19.015 - #11# - INCLUSÃƒO DE VERIFICAÃ‡ÃƒO DE CAMPOS NULOS DO RELACIONAMENTO NA TABELA DADOS_CADASTRO_XML_NFE
  -- 15/08/2017 - CARLOS ALBERTO	- ID 37560   - 02.17.020 - #10# - INCLUSÃƒO DOS CAMPOS NOME E CNPJ DO BENEFICIÃRIO.
  -- 26/04/2017 - CARLOS ALBERTO	- ID 29762   - 01.17.003 - #9#  - INCLUSÃƒO DO CAMPO DATA_APURACAO
  -- 10/11/2016 - LUCAS SOUZA		- ID 11226   - 01.16.021 - #8#  - CONSIDERAR ENDEREÃ‡O DE ENTREGA PARA A NT 2015.003
  -- 19/07/2016 - CARLOS ALBERTO    - ID 6358    - 02.16     - #7#  - AJUSTE NO VÃNCULO DAS TABELAS CTB_A_PAGAR_PARCELA COM FATURAMENTO PARA EVITAR DUPLICIDADE DE INFORMAÃ‡ÃƒO.
  -- 07/01/2016 - ADRIANO RODRIGUES - ID 1158    - 02.15.012 - #6#  - INCLUIR CAMPOS DA FILIAL PARA GERAÃ‡ÃƒO DA GNRE
  -- 22/10/2014 - CARLOS ALBERTO    - TP 6855850 - 03.14     - #5#  - AJUSTE NO VÃNCULO DAS TABELAS CTB_A_PAGAR_PARCELA COM ENTRADAS PARA EVITAR DUPLICIDADE DE INFORMAÃ‡ÃƒO.
  -- 26/03/2014 - WENDEL CRESPIGIO  - TP 5074516 - 02.14     - #4#  - INCLUSAO DO CAMPO CONCILIADO_DDA PARA SER USANDO NO FILTRO DO CURSOR DA TELA.
  -- 27/01/2014 - CARLOS ALBERTO    - TP 4810584 -           - #3#  - INCLUSÃƒO DOS CAMPOS CHAVE_XML, STATUS_NFE E TIPO_NF, TRAZIDOS DA NOTA DE ENTRADA.
  -- 13/12/2013 - CARLOS ALBERTO    - TP 4656487 -           - #2#  - INCLUSÃƒO DO CAMPO MÃ‰TODO DE PAGAMENTO, VINCULADO AO CADASTRO DO FORNECEDOR.
  -- 14/09/2012 - ALEX BORTOTO      - TP 2945050 -           - #1#  - INCLUSÃƒO DOS CAMPOS LX_STATUS_CONCILIACAO, LX_TIPO_DOCUMENTO_PARCELA
  -- 25/10/2010 - LETÃCIA           - INCLUSÃƒO DOS CAMPOS BANCO_FORNECEDOR, CC_AGENCIA, CC_CONTA
  -- 17/06/2010 - ADRIANO RODRIGUES - INCLUIR O CAMPO VALOR_PREVISAO_IMPOSTO 
  -- 06/11/2008 - ADRIANO - INCLUÃDO O CAMPO CGC_CPF DO TERCEIRO 
  -- 19/02/2008 - JOAO RICARDO - INCLUÃDO O CAMPO DE DADOS DE ARRECADACAO 
  -- 25/04/2007 - JOAO RICARDO - UTILIZAR O O CAMPO DATA_DIGITACAO DA TABELA CTB_LANCAMENTO 
  -- 14/03/2007 - ADRIANO RODRIGUES - INCLUIR OS CAMPOS CADASTRO_CLI_FOR_SACADO.CEP, CADASTRO_CLI_FOR_SACADO.CGC_CPF, CADASTRO_CLI_FOR_SACADO.ENDERECO, CADASTRO_CLI_FOR_SACADO.RG_IE, CADASTRO_CLI_FOR_SACADO.CIDADE, CADASTRO_CLI_FOR_SACADO.RAZAO_SOCIAL, CADASTRO_CLI_FOR_SACADO.TELEFONE1, CADASTRO_CLI_FOR_SACADO.UF
  -- 18/01/2006 - JOAO RICARDO - NUMERO_CORRELATIVO 
  -- 12/09/2005 - JOAO RICARDO - COD_CLIFOR DA TABELA CTB_A_PAGAR_FATURA 
  -- 12/09/2005 - JOAO RICARDO - INCLUIR CAMPO INDICA_SACADO_PRINCIPAL 
  -- 18/03/2005 - JOÃƒO RICARDO - PRAZO REAL QUANDO NÃƒO BAIXADO IGUAL AO PRAZO COMPRA 
  -- 14/03/2005 - JOÃƒO RICARDO - PRAZO DE COMPRA E PRAZO MÃ‰DIO DE PAGAMENTO 
  -- 08/12/2004 - ADRIANO RODRIGUES - ACRESCENTAR CAMPOS VALOR_FINANCEIRO E VALOR_FINANCEIRO_PADRAO
  -- 18/10/2004 - ADRIANO RODRIGUES - ACRESCENTEI OS CAMPOS SERIE_NF E NOME_RECIBO 
  -- 16/09/2004 - ADRIANO RODRIGUES - ACRESCENTEI O CAMPO VALOR_OUTRAS_ENTIDADES DA TABELA CTB_A_PAGAR_PARCELA
  -- 02/09/2004 - ADRIANO RODRIGUES - ACRESCENTEI O CAMPO TIPO DA TABELA FORNECEDORES 
  -- 15/06/2004 - JOÃƒO RICARDO - INLCUSÃƒO DO CAMPO COD_CLIFOR_SACADO 
  -- 21/10/2004 - JOÃƒO RICARDO - INCLUSÃƒO DA VIEW QUE TRAZ A CONTA DE CONTRA PARTIDA DA INCLUSÃƒO DE TÃTULO
  -- 30/10/2003 - JOÃƒO RICARDO - INCLUSÃƒO DOS CAMPOS MATRIZ_CONTABIL E COD_MATRIZ_CONTABIL DA VIEW
  --                      W_CTB_RATEIO_FILIAL_MATRIZ_CONTABIL 
  -- 07/10/2003 - 16:15 - JOÃƒO RICARDO - INCLUSÃƒO DO CAMPO DOCUMENTO DA TABELA CTB_A_PAGAR_FATURA
  -- 29/08/2003 - JOÃƒO RICARDO - INCLUSÃƒO DOS CAMPOS CIDADE, BAIRRO E UF DE COBRANÃ‡A 
  SELECT CTB_A_PAGAR_PARCELA.EMPRESA, 
         CTB_A_PAGAR_PARCELA.LANCAMENTO, 
         CTB_A_PAGAR_PARCELA.ITEM, 
         CTB_LANCAMENTO.TIPO_MOVIMENTO, 
         CTB_MOVIMENTO_TIPO.DESC_TIPO_MOVIMENTO, 
         CTB_LANCAMENTO.LOTE_LANCAMENTO, 
         CTB_LOTE.DESC_LOTE, 
         CTB_LOTE.DATA_EXPORTACAO                                                 AS DATA_LOTE,
         CTB_LOTE.CONCILIADO                                                      AS LOTE_CONCILIADO,
         CTB_LANCAMENTO.LANCAMENTO_PADRAO, 
         CTB_LANCAMENTO.GERADO_INTEGRACAO, 
         CTB_LANCAMENTO.DATA_LANCAMENTO, 
         CTB_LANCAMENTO.COD_FILIAL                                                AS COD_FILIAL_LANCAMENTO,
         FILIAIS_LANCAMENTO.FILIAL                                                AS FILIAL_LANCAMENTO,
         CTB_LANCAMENTO_ITEM.CONTA_CONTABIL, 
         CTB_CONTA_PLANO.DESC_CONTA, 
         CTB_CONTA_PLANO.CODIGO_RESUMIDO, 
         CTB_CONTA_PLANO.DESC_CONTA_REDUZIDA, 
         CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO, 
         CTB_LX_LANCAMENTO_TIPO.DESC_TIPO_LANCAMENTO, 
         CTB_LX_LANCAMENTO_TIPO.CONTA_PADRAO, 
         CTB_LX_LANCAMENTO_TIPO.CREDITO_DEBITO, 
         CTB_LX_LANCAMENTO_TIPO.INDICA_ID_CONTABIL_TERCEIRO, 
         CTB_LANCAMENTO_ITEM.HISTORICO, 
         CTB_LANCAMENTO_ITEM.CODIGO_HISTORICO, 
         CTB_LANCAMENTO_ITEM.RATEIO_CENTRO_CUSTO, 
         CTB_CENTRO_CUSTO_RATEIO.DESC_RATEIO_CENTRO_CUSTO, 
         CTB_LANCAMENTO_ITEM.CONCILIADO, 
         CTB_LANCAMENTO.DATA_DIGITACAO, 
         CTB_LANCAMENTO_ITEM.RATEIO_FILIAL, 
         CTB_FILIAL_RATEIO.DESC_RATEIO_FILIAL, 
         CTB_A_PAGAR_FATURA.COD_CLIFOR, 
         CADASTRO_CLI_FOR.NOME_CLIFOR, 
         CADASTRO_CLI_FOR.RAZAO_SOCIAL, 
         CADASTRO_CLI_FOR.CGC_CPF, 
         CTB_LANCAMENTO_ITEM.MOEDA                                                AS MOEDA_LANCAMENTO,
         CTB_LANCAMENTO_ITEM.CAMBIO_NA_DATA                                       AS CAMBIO_NA_DATA_LANCAMENTO,
         CTB_A_PAGAR_FATURA.FATURA, 
         CASE 
           WHEN CTB_A_PAGAR_FATURA.FATURA LIKE '%-%' THEN SUBSTRING(CTB_A_PAGAR_FATURA.FATURA, 1, CHARINDEX('-', CTB_A_PAGAR_FATURA.FATURA, 1) - 1)
		   WHEN CTB_A_PAGAR_FATURA.FATURA LIKE '%/%' THEN SUBSTRING(CTB_A_PAGAR_FATURA.FATURA, 1, CHARINDEX('/', CTB_A_PAGAR_FATURA.FATURA, 1) - 1)
           ELSE CTB_A_PAGAR_FATURA.FATURA 
         END                                                                      AS FATURA_GNRE,/*#6#*/
         CTB_A_PAGAR_FATURA.ESPECIE_SERIE, 
         CTB_A_PAGAR_FATURA.LX_TIPO_DOCUMENTO, 
         CTB_LX_DOCUMENTO_TIPO.TIPO_DOCUMENTO, 
         CTB_LX_DOCUMENTO_TIPO.SERIE_NF, 
         CTB_LX_DOCUMENTO_TIPO.NOME_RECIBO, 
         CTB_A_PAGAR_FATURA.EMISSAO, 
         CTB_A_PAGAR_FATURA.FATURA_SERIE, 
         CTB_A_PAGAR_FATURA.FATURA_OK, 
         CTB_A_PAGAR_FATURA.POSSUI_ENTRADA, 
         CTB_A_PAGAR_FATURA.PROVISAO, 
         CTB_A_PAGAR_FATURA.COMPLEMENTO_NOME, 
         CTB_A_PAGAR_FATURA.TAXA_JUROS, 
         CTB_A_PAGAR_FATURA.CAMBIO_NA_DATA_EMISSAO, 
         CTB_A_PAGAR_FATURA.TAXA_MULTA, 
         CTB_A_PAGAR_FATURA.DATA_ENTRADA, 
         CTB_A_PAGAR_FATURA.NUMERO_ENTRADA, 
         CTB_A_PAGAR_FATURA.NUMERO_PARCELAS, 
         CTB_A_PAGAR_FATURA.COD_FILIAL, 
         CTB_A_PAGAR_FATURA.DOCUMENTO, 
         FILIAIS.FILIAL, 
         PJ_PF_FILIAL = F.PJ_PF,/*#6#*/ 
         CNPJ_FILIAL = F.CGC_CPF,/*#6#*/ 
         RAZAO_FILIAL = F.RAZAO_SOCIAL,/*#6#*/ 
         ENDERECO_FILIAL = F.ENDERECO,/*#6#*/ 
         COD_MUNICIPIO_IBGE_FILIAL = F.COD_MUNICIPIO_IBGE,/*#6#*/ 
         UF_FILIAL = F.UF,/*#6#*/ 
         CEP_FILIAL = F.CEP,/*#6#*/ 
         TELEFONE_FILIAL = F.TELEFONE1,/*#6#*/ 
         CTB_A_PAGAR_FATURA.MOEDA, 
         CTB_A_PAGAR_PARCELA.ID_PARCELA, 
         CTB_A_PAGAR_PARCELA.BANCO, 
         CTB_A_PAGAR_PARCELA.CONTA_PORTADOR, 
         CTB_CONTA_PLANO_PORTADOR.DESC_CONTA                                      AS DESC_CONTA_PORTADOR,
         CTB_A_PAGAR_PARCELA.DATA_DESCONTO_VENC, 
         CTB_A_PAGAR_PARCELA.DESCONTO_VENC, 
         CTB_A_PAGAR_PARCELA.NUMERO_BANCARIO, 
         CTB_A_PAGAR_PARCELA.VENCIMENTO, 
         CTB_A_PAGAR_PARCELA.ID_ASSINATURA_DOCUMENTO, 
         CTB_A_PAGAR_PARCELA.DIAS_PRORROGADOS, 
         CTB_A_PAGAR_PARCELA.PAGAMENTO_APROVADO, 
         CTB_A_PAGAR_PARCELA.CODIGO_BARRA, 
         CTB_A_PAGAR_PARCELA.ID_ASSINATURA_APROVACAO, 
         CTB_A_PAGAR_PARCELA.VENCIMENTO_REAL, 
         CTB_A_PAGAR_PARCELA.VALOR_ORIGINAL, 
         CTB_A_PAGAR_PARCELA.VALOR_ORIGINAL_PADRAO, 
         CTB_A_PAGAR_PARCELA.VALOR_A_PAGAR, 
         W_CTB_A_PAGAR_PARCELA_SALDO.VALOR_A_PAGAR_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_PRINCIPAL_DEVIDO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_MULTA_GERADA, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_JUROS_GERADO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_DESCONTO_OBTIDO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_PRINCIPAL_PAGO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_MULTA_PAGA, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_JUROS_PAGO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_DESCONTO_EFETIVADO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_MULTA_GERADA, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_JUROS_GERADO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_DESCONTO_OBTIDO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_PRINCIPAL_DEVIDO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_MULTA_GERADA_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_JUROS_GERADO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.SALDO_DESCONTO_OBTIDO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_PRINCIPAL_PAGO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_MULTA_PAGA_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_JUROS_PAGO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_DESCONTO_EFETIVADO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_MULTA_GERADA_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_JUROS_GERADO_PADRAO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.TOTAL_DESCONTO_OBTIDO_PADRAO, 
         FORNECEDORES.TIPO, 
         CTB_A_PAGAR_PARCELA.CAMBIO_FIXO_PGTO, 
         FORNECEDORES.SUBTIPO_FORNECEDOR, 
         POSICAO = CASE 
                     WHEN DATEDIFF(DD, W_CTB_A_PAGAR_PARCELA_SALDO.VENCIMENTO_REAL, GETDATE()) > 0 THEN 'VENCIDOS'
                     WHEN DATEDIFF(DD, W_CTB_A_PAGAR_PARCELA_SALDO.VENCIMENTO_REAL, GETDATE()) < 0 THEN 'A VENCER'
                     WHEN DATEDIFF(DD, W_CTB_A_PAGAR_PARCELA_SALDO.VENCIMENTO_REAL, GETDATE()) = 0 THEN 'VENCENDO HOJE'
                   END, 
         PERIODO = DATEDIFF(DD, W_CTB_A_PAGAR_PARCELA_SALDO.VENCIMENTO_REAL, GETDATE()), 
         EM_CARTEIRA = CONVERT(BIT, CASE 
                                      WHEN CTB_LANCAMENTO_ITEM.CONTA_CONTABIL = CTB_A_PAGAR_PARCELA.CONTA_PORTADOR THEN 1
                                      ELSE 0 
                                    END), 
         EM_COBRANCA = CONVERT(BIT, CASE 
                                      WHEN CTB_LANCAMENTO_ITEM.CONTA_CONTABIL = CTB_A_PAGAR_PARCELA.CONTA_PORTADOR THEN 0
                                      ELSE 1 
                                    END), 
         POSSUI_DEBITO = CONVERT(BIT, 0), 
         CTB_CONTA_PLANO_PORTADOR.ID_CARTEIRA_COBRANCA, 
         CTB_CARTEIRA_COBRANCA.CARTEIRA, 
         ASSINATURA_PA.LOTE_DOCUMENTO                                             AS LOTE_DOCUMENTO_PA,
         ASSINATURA_CP.LOTE_DOCUMENTO                                             AS LOTE_DOCUMENTO_CP,
         CADASTRO_CLI_FOR.COBRANCA_CIDADE, 
         CADASTRO_CLI_FOR.COBRANCA_BAIRRO, 
         CADASTRO_CLI_FOR.COBRANCA_UF, 
         W_CTB_RATEIO_FILIAL_MATRIZ_CONTABIL.MATRIZ_CONTABIL, 
         W_CTB_RATEIO_FILIAL_MATRIZ_CONTABIL.COD_MATRIZ_CONTABIL, 
         W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA.CONTA_CONTABIL_CONTRAPARTIDA, 
         DESC_CONTA_CONTRAPARTIDA = CTB_CONTA_PLANO_CONTRAPARTIDA.DESC_CONTA, 
         CTB_A_PAGAR_FATURA.COD_CLIFOR_SACADO, 
         NOME_CLIFOR_SACADO = CADASTRO_CLI_FOR_SACADO.NOME_CLIFOR, 
         CEP_SACADO = CADASTRO_CLI_FOR_SACADO.CEP, 
         PJ_PF_SACADO = CADASTRO_CLI_FOR_SACADO.PJ_PF,/*#6#*/ 
         CNPJ_SACADO = CADASTRO_CLI_FOR_SACADO.CGC_CPF, 
         ENDERECO_SACADO = CADASTRO_CLI_FOR_SACADO.ENDERECO, 
         COD_MUNICIPIO_IBGE_SACADO = CADASTRO_CLI_FOR_SACADO.COD_MUNICIPIO_IBGE,/*#6#*/ 
         INSCRICAO_ESTADUAL_SACADO = CADASTRO_CLI_FOR_SACADO.RG_IE, 
         MUNICIPIO_SACADO = CADASTRO_CLI_FOR_SACADO.CIDADE, 
         RAZAO_SOCIAL_SACADO = CADASTRO_CLI_FOR_SACADO.RAZAO_SOCIAL, 
         TELEFONE_SACADO = CADASTRO_CLI_FOR_SACADO.TELEFONE1, 
         UF_SACADO = COALESCE(XML_NFE_E.ENTREGA_UF, XML_NFE_S.ENTREGA_UF, CADASTRO_CLI_FOR_SACADO.UF), /*#8#*/
         CAST(FORNECEDORES.TIPO AS VARCHAR(100))                                  AS TIPO_FORNECEDOR,
         CTB_A_PAGAR_PARCELA.VALOR_OUTRAS_ENTIDADES, 
         W_CTB_A_PAGAR_PARCELA_SALDO.VALOR_FINANCEIRO, 
         W_CTB_A_PAGAR_PARCELA_SALDO.VALOR_FINANCEIRO_PADRAO, 
         PRAZO_PAGAMENTO_REAL = CASE 
                                  WHEN PRAZO_PAGAMENTO_REAL = 0 THEN ABS(CAST(ISNULL(CTB_A_PAGAR_FATURA.EMISSAO, 0) AS INT) - CAST(ISNULL(CTB_A_PAGAR_PARCELA.VENCIMENTO, 0) AS INT))
                                  ELSE PRAZO_PAGAMENTO_REAL 
                                END, 
         PRAZO_COMPRA = ABS(CAST(ISNULL(CTB_A_PAGAR_FATURA.EMISSAO, 0) AS INT) - CAST(ISNULL(CTB_A_PAGAR_PARCELA.VENCIMENTO, 0) AS INT)),
         PRAZO_PAGAMENTO_MEDIO = CASE 
                                   WHEN ABS(CAST(ISNULL(CTB_A_PAGAR_FATURA.EMISSAO, 0) AS INT) - CAST(ISNULL(CTB_A_PAGAR_PARCELA.VENCIMENTO, 0) AS INT)) > PRAZO_PAGAMENTO_REAL THEN ABS(CAST(ISNULL(CTB_A_PAGAR_FATURA.EMISSAO, 0) AS INT) - CAST(ISNULL(CTB_A_PAGAR_PARCELA.VENCIMENTO, 0) AS INT))
                                   ELSE PRAZO_PAGAMENTO_REAL 
                                 END, 
         CTB_A_PAGAR_FATURA.INDICA_SACADO_PRINCIPAL, 
         CTB_LANCAMENTO.NUMERO_CORRELATIVO, 
         CTB_A_PAGAR_FATURA.ID_DADOS_ARRECADACAO, 
         CTB_A_PAGAR_PARCELA.VALOR_PREVISAO_IMPOSTO, 
         ISNULL(CADASTRO_CLI_FOR.BANCO, CTB_CONTA_PLANO.BANCO)                    AS BANCO_FORNECEDOR,
         ISNULL(CADASTRO_CLI_FOR.CC_AGENCIA, CTB_CONTA_PLANO.AGENCIA)             AS CC_AGENCIA,
         ISNULL(CADASTRO_CLI_FOR.CC_CONTA, CTB_CONTA_PLANO.NUMERO_CONTA_CORRENTE) AS CC_CONTA,
         CTB_A_PAGAR_PARCELA.LX_STATUS_CONCILIACAO,--#1# 
         CTB_A_PAGAR_PARCELA.LX_TIPO_DOCUMENTO_PARCELA, 
         TIPO_DOCUMENTO_PARCELA = CTB_LX_DOCUMENTO_TIPO_PARCELA.TIPO_DOCUMENTO,--#1# 
         CTB_LX_METODO_PAGAMENTO.METODO_PAGAMENTO,--#2# 
         ENTRADAS.CHAVE_NFE,--#3# 
         FATURAMENTO.CHAVE_NFE                                                    AS CHAVE_NFE_SAIDA, /*#6#*/
		 FATURAMENTO.INFORMACAO_COMPLEMENTAR									  AS OBS_SAIDA, /*#6#*/
         CASE 
           WHEN ENTRADAS.STATUS_NFE IN ( 49, 50, 59, 70 ) THEN 2 
           WHEN ENTRADAS.STATUS_NFE IN ( 5, 6 ) THEN 1 
           ELSE 1 
         END                                                                      AS STATUS_NFE,--#3# 
         CASE 
           WHEN ENTRADAS.NF_ENTRADA_PROPRIA = 1 THEN 1 
           ELSE 2 
         END                                                                      AS TIPO_NF,--#3# 
         CTB_A_PAGAR_PARCELA.CONCILIADO_DDA, --#4#
		 REPLICATE('0', (2 - LEN(MONTH(CTB_A_PAGAR_FATURA.EMISSAO)))) + CAST(MONTH(CTB_A_PAGAR_FATURA.EMISSAO) AS CHAR(2)) AS MES_EMISSAO, /*#6#*/
		 CAST(YEAR(CTB_A_PAGAR_FATURA.EMISSAO) AS CHAR(4)) AS ANO_EMISSAO /*#6#*/,
	    CTB_A_PAGAR_FATURA.DATA_APURACAO,  /*#9#*/
	    CTB_A_PAGAR_PARCELA.CNPJ_BENEFICIARIO,			/*#10#*/
	    CTB_A_PAGAR_PARCELA.RAZAO_SOCIAL_BENEFICIARIO	/*#10#*/
  FROM   CTB_A_PAGAR_PARCELA 
         INNER JOIN CTB_A_PAGAR_FATURA 
                 ON CTB_A_PAGAR_PARCELA.EMPRESA = CTB_A_PAGAR_FATURA.EMPRESA 
                    AND CTB_A_PAGAR_PARCELA.LANCAMENTO = CTB_A_PAGAR_FATURA.LANCAMENTO 
                    AND CTB_A_PAGAR_PARCELA.ITEM = CTB_A_PAGAR_FATURA.ITEM 
         INNER JOIN W_CTB_A_PAGAR_PARCELA_SALDO 
                 ON CTB_A_PAGAR_PARCELA.EMPRESA = W_CTB_A_PAGAR_PARCELA_SALDO.EMPRESA 
                    AND CTB_A_PAGAR_PARCELA.LANCAMENTO = W_CTB_A_PAGAR_PARCELA_SALDO.LANCAMENTO
                    AND CTB_A_PAGAR_PARCELA.ITEM = W_CTB_A_PAGAR_PARCELA_SALDO.ITEM 
                    AND CTB_A_PAGAR_PARCELA.ID_PARCELA = W_CTB_A_PAGAR_PARCELA_SALDO.ID_PARCELA
         INNER JOIN CTB_LANCAMENTO_ITEM 
                 ON CTB_A_PAGAR_PARCELA.EMPRESA = CTB_LANCAMENTO_ITEM.EMPRESA 
                    AND CTB_A_PAGAR_PARCELA.LANCAMENTO = CTB_LANCAMENTO_ITEM.LANCAMENTO 
                    AND CTB_A_PAGAR_PARCELA.ITEM = CTB_LANCAMENTO_ITEM.ITEM 
         INNER JOIN CTB_LANCAMENTO 
                 ON CTB_LANCAMENTO.EMPRESA = CTB_LANCAMENTO_ITEM.EMPRESA 
                    AND CTB_LANCAMENTO.LANCAMENTO = CTB_LANCAMENTO_ITEM.LANCAMENTO 
         INNER JOIN CTB_CONTA_PLANO 
                 ON CTB_LANCAMENTO_ITEM.CONTA_CONTABIL = CTB_CONTA_PLANO.CONTA_CONTABIL 
         INNER JOIN CTB_LX_LANCAMENTO_TIPO 
                 ON CTB_LANCAMENTO_ITEM.LX_TIPO_LANCAMENTO = CTB_LX_LANCAMENTO_TIPO.LX_TIPO_LANCAMENTO
         INNER JOIN FILIAIS 
                 ON CTB_A_PAGAR_FATURA.COD_FILIAL = FILIAIS.COD_FILIAL 
         /*#6#*/ 
         INNER JOIN CADASTRO_CLI_FOR AS F 
                 ON FILIAIS.FILIAL = F.NOME_CLIFOR 
         /*#6#*/ 
         INNER JOIN CADASTRO_CLI_FOR 
                 ON CTB_A_PAGAR_FATURA.COD_CLIFOR = CADASTRO_CLI_FOR.COD_CLIFOR 
         LEFT JOIN CADASTRO_CLI_FOR CADASTRO_CLI_FOR_SACADO 
                ON CTB_A_PAGAR_FATURA.COD_CLIFOR_SACADO = CADASTRO_CLI_FOR_SACADO.COD_CLIFOR 
         INNER JOIN FILIAIS FILIAIS_LANCAMENTO 
                 ON CTB_LANCAMENTO.COD_FILIAL = FILIAIS_LANCAMENTO.COD_FILIAL 
         LEFT JOIN FORNECEDORES 
                ON CADASTRO_CLI_FOR.COD_CLIFOR = FORNECEDORES.COD_FORNECEDOR 
         LEFT JOIN CTB_MOVIMENTO_TIPO 
                ON CTB_LANCAMENTO.TIPO_MOVIMENTO = CTB_MOVIMENTO_TIPO.TIPO_MOVIMENTO 
         LEFT JOIN CTB_CONTA_PLANO CTB_CONTA_PLANO_PORTADOR 
                ON CTB_A_PAGAR_PARCELA.CONTA_PORTADOR = CTB_CONTA_PLANO_PORTADOR.CONTA_CONTABIL
         LEFT JOIN CTB_CARTEIRA_COBRANCA 
                ON CTB_CONTA_PLANO_PORTADOR.ID_CARTEIRA_COBRANCA = CTB_CARTEIRA_COBRANCA.ID_CARTEIRA_COBRANCA
         LEFT JOIN CTB_LX_DOCUMENTO_TIPO 
                ON CTB_A_PAGAR_FATURA.LX_TIPO_DOCUMENTO = CTB_LX_DOCUMENTO_TIPO.LX_TIPO_DOCUMENTO
         LEFT JOIN CTB_FILIAL_RATEIO 
                ON CTB_LANCAMENTO_ITEM.RATEIO_FILIAL = CTB_FILIAL_RATEIO.RATEIO_FILIAL 
         LEFT JOIN CTB_CENTRO_CUSTO_RATEIO 
                ON CTB_LANCAMENTO_ITEM.RATEIO_CENTRO_CUSTO = CTB_CENTRO_CUSTO_RATEIO.RATEIO_CENTRO_CUSTO
         LEFT JOIN CTB_LOTE 
                ON CTB_LANCAMENTO.LOTE_LANCAMENTO = CTB_LOTE.LOTE_LANCAMENTO 
         LEFT JOIN AE_AUTENTICACAO ASSINATURA_CP 
                ON CTB_A_PAGAR_PARCELA.ID_ASSINATURA_DOCUMENTO = ASSINATURA_CP.ID_ASSINATURA_DOCUMENTO
         LEFT JOIN AE_AUTENTICACAO ASSINATURA_PA 
                ON CTB_A_PAGAR_PARCELA.ID_ASSINATURA_APROVACAO = ASSINATURA_PA.ID_ASSINATURA_DOCUMENTO
         LEFT JOIN W_CTB_RATEIO_FILIAL_MATRIZ_CONTABIL 
                ON W_CTB_RATEIO_FILIAL_MATRIZ_CONTABIL.RATEIO_FILIAL = CTB_LANCAMENTO_ITEM.RATEIO_FILIAL
         LEFT JOIN W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA 
                ON W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA.EMPRESA = CTB_A_PAGAR_PARCELA.EMPRESA
                   AND W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA.LANCAMENTO = CTB_A_PAGAR_PARCELA.LANCAMENTO
                   AND W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA.ITEM = CTB_A_PAGAR_PARCELA.ITEM
         LEFT JOIN CTB_CONTA_PLANO CTB_CONTA_PLANO_CONTRAPARTIDA 
                ON CTB_CONTA_PLANO_CONTRAPARTIDA.CONTA_CONTABIL = W_CTB_A_PAGAR_PARCELA_CONTA_CONTRAPARTIDA.CONTA_CONTABIL_CONTRAPARTIDA
         LEFT JOIN CTB_LX_DOCUMENTO_TIPO CTB_LX_DOCUMENTO_TIPO_PARCELA 
                ON CTB_A_PAGAR_PARCELA.LX_TIPO_DOCUMENTO_PARCELA = CTB_LX_DOCUMENTO_TIPO_PARCELA.LX_TIPO_DOCUMENTO
         LEFT JOIN CTB_LX_METODO_PAGAMENTO CTB_LX_METODO_PAGAMENTO 
                ON CTB_A_PAGAR_PARCELA.LX_METODO_PAGAMENTO_PARCELA = CTB_LX_METODO_PAGAMENTO.LX_METODO_PAGAMENTO --#2# 
         --#3# 
         LEFT JOIN ENTRADAS 
                ON ENTRADAS.CTB_LANCAMENTO = CTB_A_PAGAR_FATURA.LANCAMENTO 
                   AND ENTRADAS.CTB_ITEM = CTB_A_PAGAR_FATURA.ITEM 
                   AND ENTRADAS.EMPRESA = CTB_A_PAGAR_FATURA.EMPRESA 
                   AND ENTRADAS.FATURA = CTB_A_PAGAR_FATURA.FATURA --#5# 
                   AND ENTRADAS.NOME_CLIFOR = CADASTRO_CLI_FOR.NOME_CLIFOR --#5# 
         /*#6#*/ 
         LEFT JOIN DBO.FATURAMENTO 
                ON FATURAMENTO.CTB_LANCAMENTO = CTB_A_PAGAR_FATURA.LANCAMENTO 
				   AND FATURAMENTO.CTB_ITEM = CTB_A_PAGAR_FATURA.ITEM	/*#7#*/
                   AND FATURAMENTO.EMPRESA = CTB_A_PAGAR_FATURA.EMPRESA 
                   AND FATURAMENTO.FILIAL = FILIAIS.FILIAL
		 LEFT JOIN DBO.DADOS_CADASTRO_XML_NFE XML_NFE_E (NOLOCK) /*#8#*/
				ON XML_NFE_E.NF_ENTRADA IS NOT NULL  /*#11#*/
				AND XML_NFE_E.SERIE_NF_ENTRADA IS NOT NULL   /*#11#*/
				AND XML_NFE_E.NOME_CLIFOR IS NOT NULL  /*#11#*/
				AND XML_NFE_E.NF_ENTRADA			= ENTRADAS.NF_ENTRADA /*#8#*/
				AND XML_NFE_E.SERIE_NF_ENTRADA	= ENTRADAS.SERIE_NF /*#8#*/
				AND XML_NFE_E.NOME_CLIFOR		= ENTRADAS.NOME_CLIFOR /*#8#*/
				AND ENTRADAS.INDICA_ENDERECO_ENTREGA = 1 /*#8#*/
		 LEFT JOIN DBO.DADOS_CADASTRO_XML_NFE XML_NFE_S (NOLOCK) /*#8#*/
				ON  XML_NFE_S.NF_SAIDA IS NOT NULL  /*#11#*/
				AND XML_NFE_S.SERIE_NF IS NOT NULL  /*#11#*/
				AND XML_NFE_S.FILIAL IS NOT NULL  /*#11#*/
				AND XML_NFE_S.NF_SAIDA		= FATURAMENTO.NF_SAIDA /*#8#*/
				AND XML_NFE_S.SERIE_NF		= FATURAMENTO.SERIE_NF /*#8#*/
				AND XML_NFE_S.FILIAL		= FATURAMENTO.FILIAL /*#8#*/
				AND FATURAMENTO.INDICA_ENDERECO_ENTREGA = 1 /*#8#*/				   
				   